=== telerik/kendo-themes/packages/html-spec/schemas/component.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "kendo-html://schemas/kendo-html-spec.json",
    "title": "Schema definition for Kendo UI HTML Specification",
    "description": "The HTML specification schema for Kendo UI",
    "type": "object",
    "$definitions": {
        "component-state": { "$ref": "./component-state.schema.json#/definitions/component-state" },
        "component-option": { "$ref": "./component-option.schema.json#/definitions/component-option" },
        "component-child": { "$ref": "./component-child.schema.json#/definitions/component-child" }
    },
    "properties": {
        "title": {
            "description": "Title of the HTML spec file",
            "type": "string"
        },
        "component": {
            "description": "Name of the component",
            "type": "string"
        },
        "selector": {
            "description": "The selector/s that can target the component",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "string"
            }
        },
        "states": {
            "description": "Describes the component states",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-state"
            }
        },
        "options": {
            "description": "Describes the component options",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-option"
            }
        },
        "children": {
            "description": "Describes the component children",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-child"
            }
        }
    },
    "required": [
        "$schema",
        "title",
        "component",
        "selector"
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/table/table.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Table HTML Spec",
    "component": "table",
    "selector": [
        ".k-table"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-table-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-table-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-table-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "table-head",
            "selector": [
                ".k-table-thead"
            ],
            "children": [
                {
                    "name": "table-header-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "children": [
                        {
                            "name": "table-header-cell",
                            "selector": [
                                ".k-table-th"
                            ],
                            "states": [
                                {
                                    "name": "focus",
                                    "selector": [
                                        ":focus",
                                        ".k-focus"
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name": "table-body",
            "selector": [
                ".k-table-tbody"
            ],
            "children": [
                {
                    "name": "table-body-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "states": [
                        {
                            "name": "hover",
                            "selector": [
                                ":hover",
                                ".k-hover"
                            ]
                        },
                        {
                            "name": "focus",
                            "selector": [
                                ":focus",
                                ".k-focus"
                            ]
                        },
                        {
                            "name": "selected",
                            "selector": [
                                ".k-selected"
                            ]
                        },
                        {
                            "name": "alt",
                            "selector": [
                                ".k-table-alt-row"
                            ]
                        }
                    ],
                    "children": [
                        {
                            "name": "table-body-cell",
                            "selector": [
                                ".k-table-td"
                            ],
                            "states": [
                                {
                                    "name": "hover",
                                    "selector": [
                                        ":hover",
                                        ".k-hover"
                                    ]
                                },
                                {
                                    "name": "focus",
                                    "selector": [
                                        ":focus",
                                        ".k-focus"
                                    ]
                                },
                                {
                                    "name": "selected",
                                    "selector": [
                                        ".k-selected"
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "table-group-row",
                    "selector": [
                        ".k-table-group-row"
                    ],
                    "children": [
                        {
                            "name": "table-group-cell",
                            "selector": [
                                ".k-table-th"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name": "table-footer",
            "selector": [
                ".k-table-tfoot"
            ],
            "children": [
                {
                    "name": "table-footer-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "children": [
                        {
                            "name": "table-footer-cell",
                            "selector": [
                                ".k-table-td"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/data-table/data-table-header.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Data Table Header HTML Spec",
    "component": "data-table-header-table",
    "selector": [
        ".k-table"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-table-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-table-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-table-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "data-table-header-table-head",
            "selector": [
                ".k-table-thead"
            ],
            "children": [
                {
                    "name": "data-table-header-table-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "children": [
                        {
                            "name": "data-table-header-table-cell",
                            "selector": [
                                ".k-table-th"
                            ],
                            "states": [
                                {
                                    "name": "focus",
                                    "selector": [
                                        ":focus",
                                        ".k-focus"
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/grid/grid-column-menu.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Grid Column Menu HTML Spec",
    "component": "grid-column-menu",
    "selector": [
        ".k-grid-columnmenu-popup"
    ],
    "children": [
        {
            "name": "grid-column-menu-wrap",
            "selector": [
                ".k-columnmenu-item-wrapper"
            ]
        },
        {
            "name": "grid-column-menu-item",
            "selector": [
                ".k-columnmenu-item"
            ],
            "children": [
                {
                    "name": "grid-column-menu-icon",
                    "$ref": "icon",
                    "selector": [
                        ".k-icon"
                    ]
                }
            ]
        },
        {
            "name": "grid-filter-menu-container",
            "selector": [
                ".k-filter-menu-container"
            ]
        },
        {
            "name": "grid-filter-menu-item",
            "selector": [
                ".k-multicheck-wrap .k-item"
            ]
        },
        {
            "name": "grid-filter-selected-items",
            "selector": [
                ".k-filter-selected-items"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/popup/popup.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Popup HTML Spec",
    "component": "popup",
    "selector": [
        ".k-popup"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-popup-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-popup-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-popup-lg"
                    ]
                }
            ]
        },
        {
            "name": "rounded",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-rounded-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-rounded-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-rounded-lg"
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/notification/notification.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Notification HTML Spec",
    "component": "notification",
    "selector": [
        ".k-notification"
    ],
    "options": [
        {
            "name": "themeColor",
            "values": [
                {
                    "name": "primary",
                    "selector": [
                        ".k-notification-primary"
                    ]
                },
                {
                    "name": "secondary",
                    "selector": [
                        ".k-notification-secondary"
                    ]
                },
                {
                    "name": "tertiary",
                    "selector": [
                        ".k-notification-tertiary"
                    ]
                },
                {
                    "name": "info",
                    "selector": [
                        ".k-notification-info"
                    ]
                },
                {
                    "name": "success",
                    "selector": [
                        ".k-notification-success"
                    ]
                },
                {
                    "name": "warning",
                    "selector": [
                        ".k-notification-warning"
                    ]
                },
                {
                    "name": "error",
                    "selector": [
                        ".k-notification-error"
                    ]
                },
                {
                    "name": "dark",
                    "selector": [
                        ".k-notification-dark"
                    ]
                },
                {
                    "name": "light",
                    "selector": [
                        ".k-notification-light"
                    ]
                },
                {
                    "name": "inverse",
                    "selector": [
                        ".k-notification-inverse"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "notification-status-icon",
            "$ref": "icon",
            "selector": [
                ".k-notification-status"
            ]
        },
        {
            "name": "notification-content",
            "selector": [
                ".k-notification-content"
            ]
        },
        {
            "name": "notification-action",
            "$ref": "icon",
            "selector": [
                ".k-notification-action"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/dropdownlist/dropdown.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Dropdown HTML Spec",
    "component": "dropdown",
    "selector": [
        ".k-dropdown",
        ".k-dropdown-list",
        ".k-dropdownlist"
    ],
    "states": [
        {
            "name": "hover",
            "selector": [
                ":hover",
                ".k-hover"
            ]
        },
        {
            "name": "focus",
            "selector": [
                ":focus",
                ":focus-within",
                ".k-focus"
            ]
        },
        {
            "name": "valid",
            "selector": [
                ".k-valid",
                ".ng-valid.ng-touched",
                ".ng-valid.ng-dirty"
            ]
        },
        {
            "name": "invalid",
            "selector": [
                ".k-invalid",
                ".ng-invalid.ng-touched",
                ".ng-invalid.ng-dirty"
            ]
        },
        {
            "name": "disabled",
            "selector": [
                ":disabled",
                "[disabled]",
                ".k-disabled"
            ]
        }
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-picker-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-picker-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-picker-lg"
                    ]
                }
            ]
        },
        {
            "name": "rounded",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-rounded-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-rounded-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-rounded-lg"
                    ]
                },
                {
                    "name": "full",
                    "selector": [
                        ".k-rounded-full"
                    ]
                }
            ]
        },
        {
            "name": "fillMode",
            "values": [
                {
                    "name": "solid",
                    "selector": [
                        ".k-picker-solid"
                    ]
                },
                {
                    "name": "flat",
                    "selector": [
                        ".k-picker-flat"
                    ]
                },
                {
                    "name": "outline",
                    "selector": [
                        ".k-picker-outline"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "inner-input",
            "selector": [
                ".k-input-inner"
            ]
        },
        {
            "name": "input-button",
            "$ref": "button",
            "selector": [
                ".k-input-button"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                },
                {
                    "name": "fillMode",
                    "value": "{parent.fillMode}"
                },
                {
                    "name": "themeColor",
                    "value": "{parent.themeColor}"
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/progressbar/chunk-progressbar.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Chunk Progressbar HTML Spec",
    "component": "chunk-progressbar",
    "selector": [
        ".k-chunk-progressbar"
    ],
    "states": [
        {
            "name": "indeterminate",
            "selector": [
                ".k-progressbar-indeterminate"
            ]
        },
        {
            "name": "disabled",
            "selector": [
                ":disabled",
                "[disabled]",
                ".k-disabled"
            ]
        }
    ],
    "options": [
        {
            "name": "orientation",
            "values": [
                {
                    "name": "horizontal",
                    "selector": [
                        ".k-progressbar-horizontal"
                    ]
                },
                {
                    "name": "vertical",
                    "selector": [
                        ".k-progressbar-vertical"
                    ]
                },
                {
                    "name": "reverse",
                    "selector": [
                        ".k-progressbar-reverse"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "progressbar-chunk",
            "selector": [
                ".k-progressbar-chunk"
            ],
            "states": [
                {
                    "name": "selected",
                    "selector": [
                        ".k-selected"
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/data-table/data-table-footer.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Data Table Footer HTML Spec",
    "component": "data-table-footer-table",
    "selector": [
        ".k-table"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-table-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-table-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-table-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "data-table-footer-table-tfoot",
            "selector": [
                ".k-table-tfoot"
            ],
            "children": [
                {
                    "name": "data-table-footer-table-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "children": [
                        {
                            "name": "data-table-footer-table-cell",
                            "selector": [
                                ".k-table-td"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}
