=== telerik/kendo-themes/packages/html-spec/schemas/component.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "kendo-html://schemas/kendo-html-spec.json",
    "title": "Schema definition for Kendo UI HTML Specification",
    "description": "The HTML specification schema for Kendo UI",
    "type": "object",
    "$definitions": {
        "component-state": { "$ref": "./component-state.schema.json#/definitions/component-state" },
        "component-option": { "$ref": "./component-option.schema.json#/definitions/component-option" },
        "component-child": { "$ref": "./component-child.schema.json#/definitions/component-child" }
    },
    "properties": {
        "title": {
            "description": "Title of the HTML spec file",
            "type": "string"
        },
        "component": {
            "description": "Name of the component",
            "type": "string"
        },
        "selector": {
            "description": "The selector/s that can target the component",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "string"
            }
        },
        "states": {
            "description": "Describes the component states",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-state"
            }
        },
        "options": {
            "description": "Describes the component options",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-option"
            }
        },
        "children": {
            "description": "Describes the component children",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-child"
            }
        }
    },
    "required": [
        "$schema",
        "title",
        "component",
        "selector"
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/grid-layout/grid-layout.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Grid Layout HTML Spec",
    "component": "grid-layout",
    "selector": [
        ".k-grid-layout"
    ],
    "options": [
        {
            "name": "align-items-inline",
            "values": [
                {
                    "name": "start",
                    "selector": [
                        ".k-justify-items-start"
                    ]
                },
                {
                    "name": "center",
                    "selector": [
                        ".k-justify-items-center"
                    ]
                },
                {
                    "name": "end",
                    "selector": [
                        ".k-justify-items-end"
                    ]
                },
                {
                    "name": "stretch",
                    "selector": [
                        ".k-justify-items-stretch"
                    ]
                }
            ]
        },
        {
            "name": "align-items-block",
            "values": [
                {
                    "name": "start",
                    "selector": [
                        ".k-align-items-start"
                    ]
                },
                {
                    "name": "center",
                    "selector": [
                        ".k-align-items-center"
                    ]
                },
                {
                    "name": "end",
                    "selector": [
                        ".k-align-items-end"
                    ]
                },
                {
                    "name": "stretch",
                    "selector": [
                        ".k-align-items-stretch"
                    ]
                },
                {
                    "name": "baseline",
                    "selector": [
                        ".k-align-items-baseline"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "grid-layout-item"
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/loader/loader-container.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Loader Container HTML Spec",
    "component": "loader-container",
    "selector": [
        ".k-loader-container"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-loader-container-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-loader-container-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-loader-container-lg"
                    ]
                }
            ]
        },
        {
            "name": "position",
            "values": [
                {
                    "name": "top",
                    "selector": [
                        ".k-loader-top"
                    ]
                },
                {
                    "name": "end",
                    "selector": [
                        ".k-loader-end"
                    ]
                },
                {
                    "name": "start",
                    "selector": [
                        ".k-loader-start"
                    ]
                }
            ]
        },
        {
            "name": "overlay",
            "values": [
                {
                    "name": "light"
                },
                {
                    "name": "dark"
                }
            ]
        }
    ],
    "children": [
        {
            "name": "loader-container-overlay",
            "selector": [
                ".k-loader-container-overlay.k-overlay-{parent.overlay}"
            ]
        },
        {
            "name": "loader-container-inner",
            "selector": [
                ".k-loader-container-inner"
            ],
            "children": [
                {
                    "name": "loader",
                    "$ref": "loader",
                    "selector": [
                        ".k-loader"
                    ],
                    "options": [
                        {
                            "name": "size",
                            "value": "{parent.size}"
                        },
                        {
                            "name": "themeColor",
                            "value": "{parent.themeColor}"
                        },
                        {
                            "name": "animation",
                            "value": "{parent.loaderType}"
                        }
                    ]
                },
                {
                    "name": "loader-container-label",
                    "selector": [
                        ".k-loader-container-label.\\!k-text-{parent.themeColor}"
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/data-table/data-table-scroller.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Data Table Scroller HTML Spec",
    "component": "data-table-scroller-table",
    "selector": [
        ".k-table"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-table-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-table-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-table-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "data-table-scroller-table-body",
            "selector": [
                ".k-table-tbody"
            ],
            "children": [
                {
                    "name": "data-table-scroller-table-row",
                    "selector": [
                        ".k-table-row"
                    ],
                    "states": [
                        {
                            "name": "hover",
                            "selector": [
                                ":hover",
                                ".k-hover"
                            ]
                        },
                        {
                            "name": "focus",
                            "selector": [
                                ":focus",
                                ".k-focus"
                            ]
                        },
                        {
                            "name": "selected",
                            "selector": [
                                ".k-selected"
                            ]
                        },
                        {
                            "name": "alt",
                            "selector": [
                                ".k-table-alt-row"
                            ]
                        }
                    ],
                    "children": [
                        {
                            "name": "data-table-scroller-table-cell",
                            "selector": [
                                ".k-table-td"
                            ],
                            "states": [
                                {
                                    "name": "hover",
                                    "selector": [
                                        ":hover",
                                        ".k-hover"
                                    ]
                                },
                                {
                                    "name": "focus",
                                    "selector": [
                                        ":focus",
                                        ".k-focus"
                                    ]
                                },
                                {
                                    "name": "selected",
                                    "selector": [
                                        ".k-selected"
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    "name": "data-table-scroller-table-group-row",
                    "selector": [
                        ".k-table-group-row"
                    ],
                    "children": [
                        {
                            "name": "data-table-scroller-table-group-cell",
                            "selector": [
                                ".k-table-th"
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/pager/pager.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Pager HTML Spec",
    "component": "pager",
    "selector": [
        ".k-pager"
    ],
    "states": [
        {
            "name": "focus",
            "selector": [
                ":focus",
                ".k-focus"
            ]
        },
        {
            "name": "disabled",
            "selector": [
                ":disabled",
                "[disabled]",
                ".k-disabled"
            ]
        }
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-pager-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-pager-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-pager-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "pager-nav",
            "$ref": "button",
            "selector": [
                ".k-pager-nav"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                },
                {
                    "name": "fillMode",
                    "value": "flat"
                }
            ]
        },
        {
            "name": "pager-numbers",
            "$ref": "button",
            "selector": [
                ".k-pager-numbers .k-button"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                },
                {
                    "name": "fillMode",
                    "value": "flat"
                },
                {
                    "name": "themeColor",
                    "value": "primary"
                }
            ]
        },
        {
            "name": "pager-refresh",
            "$ref": "button",
            "selector": [
                ".k-pager-refresh"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                },
                {
                    "name": "fillMode",
                    "value": "flat"
                }
            ]
        },
        {
            "name": "pager-select",
            "$ref": "dropdown",
            "selector": [
                "select.k-dropdown"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                }
            ]
        },
        {
            "name": "pager-input",
            "$ref": "textbox",
            "selector": [
                ".k-pager-input > .k-textbox"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                }
            ]
        },
        {
            "name": "k-pager-dropdown",
            "$ref": "dropdown",
            "selector": [
                ".k-pager-sizes > .k-dropdown"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                }
            ]
        },
        {
            "name": "pager-info",
            "selector": [
                ".k-pager-info"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/progressbar/progressbar.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Progressbar HTML Spec",
    "component": "progressbar",
    "selector": [
        ".k-progressbar"
    ],
    "states": [
        {
            "name": "indeterminate",
            "selector": [
                ".k-progressbar-indeterminate"
            ]
        },
        {
            "name": "disabled",
            "selector": [
                ":disabled",
                "[disabled]",
                ".k-disabled"
            ]
        }
    ],
    "options": [
       {
            "name": "orientation",
            "values": [
                {
                    "name": "horizontal",
                    "selector": [
                        ".k-progressbar-horizontal"
                    ]
                },
                {
                    "name": "vertical",
                    "selector": [
                        ".k-progressbar-vertical"
                    ]
                },
                {
                    "name": "reverse",
                    "selector": [
                        ".k-progressbar-reverse"
                    ]
                }
            ]
       }
    ],
    "children": [
        {
            "name": "progressbar-value",
            "selector": [
                ".k-progressbar-value.k-selected"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/textbox/textbox.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Textbox HTML Spec",
    "component": "textbox",
    "selector": [
        ".k-textbox"
    ],
    "states": [
        {
            "name": "hover",
            "selector": [
                ":hover",
                ".k-hover"
            ]
        },
        {
            "name": "focus",
            "selector": [
                ":focus",
                ":focus-within",
                ".k-focus"
            ]
        },
        {
            "name": "valid",
            "selector": [
                ".k-valid",
                ".ng-valid.ng-touched",
                ".ng-valid.ng-dirty"
            ]
        },
        {
            "name": "invalid",
            "selector": [
                ".k-invalid",
                ".ng-invalid.ng-touched",
                ".ng-invalid.ng-dirty"
            ]
        },
        {
            "name": "disabled",
            "selector": [
                ":disabled",
                "[disabled]",
                ".k-disabled"
            ]
        }
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-input-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-input-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-input-lg"
                    ]
                }
            ]
        },
        {
            "name": "rounded",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-rounded-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-rounded-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-rounded-lg"
                    ]
                },
                {
                    "name": "full",
                    "selector": [
                           ".k-rounded-full"
                    ]
                }
            ]
        },
        {
            "name": "fillMode",
            "values": [
                {
                    "name": "solid",
                    "selector": [
                        ".k-input-solid"
                    ]
                },
                {
                    "name": "flat",
                    "selector": [
                        ".k-input-flat"
                    ]
                },
                {
                    "name": "outline",
                    "selector": [
                        ".k-input-outline"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "inner-input",
            "selector": [
                ".k-inner-input"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/list/list.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo List HTML Spec",
    "component": "list",
    "selector": [
        ".k-list"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-list-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-list-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-list-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "list-item",
            "$ref": "list-item",
            "selector": [
                ".k-list-item"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/icon/icon.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Icon HTML Spec",
    "component": "icon",
    "selector": [
        ".k-icon"
    ],
    "options": [
        {
            "name": "name",
            "values": [
                {
                    "name": "*",
                    "selector": [
                        ".k-i-{options.name}"
                    ]
                }
            ]
        }
    ]
}
