=== telerik/kendo-themes/packages/html-spec/schemas/component.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "kendo-html://schemas/kendo-html-spec.json",
    "title": "Schema definition for Kendo UI HTML Specification",
    "description": "The HTML specification schema for Kendo UI",
    "type": "object",
    "$definitions": {
        "component-state": { "$ref": "./component-state.schema.json#/definitions/component-state" },
        "component-option": { "$ref": "./component-option.schema.json#/definitions/component-option" },
        "component-child": { "$ref": "./component-child.schema.json#/definitions/component-child" }
    },
    "properties": {
        "title": {
            "description": "Title of the HTML spec file",
            "type": "string"
        },
        "component": {
            "description": "Name of the component",
            "type": "string"
        },
        "selector": {
            "description": "The selector/s that can target the component",
            "type": "array",
            "minItems": 1,
            "items": {
                "type": "string"
            }
        },
        "states": {
            "description": "Describes the component states",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-state"
            }
        },
        "options": {
            "description": "Describes the component options",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-option"
            }
        },
        "children": {
            "description": "Describes the component children",
            "type": "array",
            "items": {
                "$ref": "#/$definitions/component-child"
            }
        }
    },
    "required": [
        "$schema",
        "title",
        "component",
        "selector"
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/dialog/dialog.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Dialog HTML Spec",
    "component": "dialog",
    "selector": [
        ".k-dialog"
    ],
    "options": [
        {
            "name": "themeColor",
            "values": [
                {
                    "name": "primary",
                    "selector": [
                        ".k-dialog-primary"
                    ]
                },
                {
                    "name": "dark",
                    "selector": [
                        ".k-dialog-dark"
                    ]
                },
                {
                    "name": "light",
                    "selector": [
                        ".k-dialog-light"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "dialog-titlebar",
            "selector": [
                ".k-dialog-titlebar"
            ]
        },
        {
            "name": "dialog-title",
            "selector": [
                ".k-dialog-title"
            ]
        },
        {
            "name": "dialog-actions",
            "selector": [
                ".k-dialog-titlebar-actions"
            ]
        },
        {
            "name": "dialog-action",
            "$ref": "button",
            "selector": [
                ".k-dialog-action"
            ],
            "options": [
                {
                    "name": "fillMode",
                    "value": "flat"
                }
            ]
        },
        {
            "name": "dialog-content",
            "selector": [
                ".k-dialog-content"
            ]
        },
        {
            "name": "dialog-buttons",
            "$ref": "action-buttons",
            "selector": [
                ".k-dialog-actions"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/listview/listview.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Listview HTML Spec",
    "component": "listview",
    "selector": [
        ".k-listview"
    ],
    "children": [
        {
            "name": "listview-header",
            "selector": [
                ".k-listview-header"
            ]
        },
        {
            "name": "listview-content",
            "selector": [
                ".k-listview-content"
            ],
            "children": [
                {
                    "name": "listview-item",
                    "selector": [
                        ".k-listview-item"
                    ],
                    "states": [
                        {
                            "name": "focus",
                            "selector": [
                                ":focus",
                                ".k-focus"
                            ]
                        },
                        {
                            "name":"selected",
                            "selector": [
                                ".k-selected"
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "name": "listview-footer",
            "selector": [
                ".k-listview-footer"
            ]
        },
        {
            "name": "listview-pager",
            "$ref": "pager",
            "selector": [
                ".k-listview-pager"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/data-table/data-table.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Data Table HTML Spec",
    "component": "data-table",
    "selector": [
        ".k-data-table"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-table-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-table-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-table-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "data-table-header",
            "$ref": "data-table-header",
            "selector": [
                ".k-table-header"
            ],
            "children": [
                {
                    "name": "data-table-header-wrap",
                    "selector": [
                        ".k-table-header-wrap"
                    ]
                },
                {
                    "name": "data-table-header-table",
                    "$ref": "data-table-header-table",
                    "selector": [
                        ".k-table"
                    ]
                }
            ]
        },
        {
            "name": "data-table-scroller",
            "selector": [
                ".k-table-scroller"
            ],
            "children": [
                {
                    "name": "data-table-scroller-table",
                    "$ref": "data-table-scroller-table",
                    "selector": [
                        ".k-table"
                    ]
                }
            ]
        },
        {
            "name": "data-table-footer",
            "selector": [
                ".k-table-footer"
            ],
            "children": [
                {
                    "name": "data-table-footer-table",
                    "$ref": "data-table-footer-table",
                    "selector": [
                        ".k-table"
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/button/button.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Button HTML Spec",
    "component": "button",
    "selector": [
        ".k-button"
    ],
    "states": [
        {
            "name": "hover",
            "selector": [
                ":hover",
                ".k-hover"
            ]
        },
        {
            "name": "focus",
            "selector": [
                ":focus",
                ".k-focus"
            ]
        },
        {
            "name": "active",
            "selector": [
                ":active",
                ".k-active"
            ]
        },
        {
            "name": "selected",
            "selector": [
                ".k-selected"
            ]
        },
        {
            "name": "disabled",
            "selector": [
                ":disabled",
                "[disabled]",
                ".k-disabled"
            ]
        }
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-button-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-button-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-button-lg"
                    ]
                }
            ]
        },
        {
            "name": "rounded",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-rounded-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-rounded-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-rounded-lg"
                    ]
                },
                {
                    "name": "full",
                    "selector": [
                        ".k-rounded-full"
                    ]
                }
            ]
        },
        {
            "name": "fillMode",
            "values": [
                {
                    "name": "solid",
                    "selector": [
                        ".k-button-solid"
                    ]
                },
                {
                    "name": "flat",
                    "selector": [
                        ".k-button-flat"
                    ]
                },
                {
                    "name": "outline",
                    "selector": [
                        ".k-button-outline"
                    ]
                },
                {
                    "name": "link",
                    "selector": [
                        ".k-button-link"
                    ]
                }
            ]
        },
        {
            "name": "themeColor",
            "values": [
                {
                    "name": "base",
                    "selector": [
                        ".k-button-{options.fillMode}-base"
                    ]
                },
                {
                    "name": "primary",
                    "selector": [
                        ".k-button-{options.fillMode}-primary"
                    ]
                },
                {
                    "name": "secondary",
                    "selector": [
                        ".k-button-{options.fillMode}-secondary"
                    ]
                },
                {
                    "name": "tertiary",
                    "selector": [
                        ".k-button-{options.fillMode}-tertiary"
                    ]
                },
                {
                    "name": "info",
                    "selector": [
                        ".k-button-{options.fillMode}-info"
                    ]
                },
                {
                    "name": "success",
                    "selector": [
                        ".k-button-{options.fillMode}-success"
                    ]
                },
                {
                    "name": "warning",
                    "selector": [
                        ".k-button-{options.fillMode}-warning"
                    ]
                },
                {
                    "name": "error",
                    "selector": [
                        ".k-button-{options.fillMode}-error"
                    ]
                },
                {
                    "name": "dark",
                    "selector": [
                        ".k-button-{options.fillMode}-dark"
                    ]
                },
                {
                    "name": "light",
                    "selector": [
                        ".k-button-{options.fillMode}-light"
                    ]
                },
                {
                    "name": "inverse",
                    "selector": [
                        ".k-button-{options.fillMode}-inverse"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "button-icon",
            "$ref": "icon",
            "selector": [
                ".k-button-icon"
            ]
        },
        {
            "name": "button-text",
            "selector": [
                ".k-button-text"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/loader/loader.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Loader HTML Spec",
    "component": "loader",
    "selector": [
        ".k-loader"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-loader-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-loader-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-loader-lg"
                    ]
                }
            ]
        },
        {
            "name": "themeColor",
            "values": [
                {
                    "name": "primary",
                    "selector": [
                        ".k-loader-primary"
                    ]
                },
                {
                    "name": "secondary",
                    "selector": [
                        ".k-loader-secondary"
                    ]
                },
                {
                    "name": "tertiary",
                    "selector": [
                        ".k-loader-tertiary"
                    ]
                },
                {
                    "name": "info",
                    "selector": [
                        ".k-loader-info"
                    ]
                },
                {
                    "name": "success",
                    "selector": [
                        ".k-loader-success"
                    ]
                },
                {
                    "name": "warning",
                    "selector": [
                        ".k-loader-warning"
                    ]
                },
                {
                    "name": "error",
                    "selector": [
                        ".k-loader-error"
                    ]
                },
                {
                    "name": "dark",
                    "selector": [
                        ".k-loader-dark"
                    ]
                },
                {
                    "name": "light",
                    "selector": [
                        ".k-loader-light"
                    ]
                },
                {
                    "name": "inverse",
                    "selector": [
                        ".k-loader-inverse"
                    ]
                }
            ]
        },
        {
            "name": "animation",
            "values": [
                {
                    "name": "pulsing",
                    "selector": [
                        ".k-loader-pulsing-2"
                    ]
                },
                {
                    "name": "infinite-spinner",
                    "selector": [
                        ".k-loader-spinner-3"
                    ]
                },
                {
                    "name": "converging-spinner",
                    "selector": [
                        ".k-loader-spinner-4"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "loader-canvas",
            "selector": [
                ".k-loader-canvas"
            ],
            "children": [
                {
                    "name": "loader-segment",
                    "selector": [
                        ".k-loader-segment"
                    ]
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/editor/editor.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Editor HTML Spec",
    "component": "editor",
    "selector": [
        ".k-editor"
    ],
    "states": [
        {
            "name": "resizable",
            "selector": [
                ".k-editor-resizable"
            ]
        },
        {
            "name": "readonly",
            "selector": [
                ".k-readonly"
            ]
        }
    ],
    "children": [
        {
            "name": "editor-toolbar",
            "$ref": "toolbar",
            "selector": [
                ".k-editor-toolbar"
            ]
        },
        {
            "name": "editor-content",
            "selector": [
                ".k-editor-content"
            ],
            "states": [
                {
                    "name": "focus",
                    "selector": [
                        ".k-focus"
                    ]
                }
            ],
            "children": [
                {
                    "name": "text-selected",
                    "selector": [
                        ".k-text-selected"
                    ]
                },
                {
                    "name": "text-highlighted",
                    "selector": [
                        ".k-text-highlighted"
                    ]
                }
            ]
        },
        {
            "name": "editor-resize-handle",
            "selector": [
                ".k-editor-resize-handle"
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/toolbar/toolbar.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Toolbar HTML Spec",
    "component": "toolbar",
    "selector": [
        ".k-toolbar"
    ],
    "states": [
        {
            "name": "focus",
            "selector": [
                ":focus",
                ".k-focus"
            ]
        }
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-toolbar-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-toolbar-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-toolbar-lg"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "toolbar-spacer",
            "selector": [
                ".k-spacer",
                ".k-toolbar-spacer"
            ]
        },
        {
            "name": "toolbar-separator",
            "selector": [
                ".k-separator",
                ".k-toolbar-separator"
            ]
        },
        {
            "name": "toolbar-item",
            "selector": [
                ".k-toolbar-item"
            ],
            "states": [
                {
                    "name": "focus",
                    "selector": [
                        ":focus",
                        ".k-focus"
                    ]
                }
            ]
        },
        {
            "name": "toolbar-overflow-button",
            "$ref": "button",
            "selector": [
                ".k-toolbar-overflow-button"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                },
                {
                    "name": "fillMode",
                    "value": "flat"
                }
            ]
        },
        {
            "name": "toolbar-button",
            "$ref": "button",
            "selector": [
                ".k-toolbar-button"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                }
            ]
        },
        {
            "name": "toolbar-toggle-button",
            "$ref": "button",
            "selector": [
                ".k-toolbar-toggle-button"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                }
            ]
        },
        {
            "name": "toolbar-button-group",
            "$ref": "button-group",
            "selector": [
                ".k-toolbar-button-group"
            ]
        },
        {
            "name": "toolbar-menu-button",
            "$ref": "menu-button",
            "selector": [
                ".k-toolbar-menu-button"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                }
            ]
        },
        {
            "name": "toolbar-split-button",
            "$ref": "split-button",
            "selector": [
                ".k-toolbar-split-button"
            ],
            "options": [
                {
                    "name": "size",
                    "value": "{parent.size}"
                }
            ]
        }
    ]
}

=== telerik/kendo-themes/packages/html-spec/src/forms/forms.json
{
    "$schema": "../../schemas/component.schema.json",
    "title": "Kendo Forms HTML Spec",
    "component": "forms",
    "selector": [
        ".k-form"
    ],
    "options": [
        {
            "name": "size",
            "values": [
                {
                    "name": "small",
                    "selector": [
                        ".k-form-sm"
                    ]
                },
                {
                    "name": "medium",
                    "selector": [
                        ".k-form-md"
                    ]
                },
                {
                    "name": "large",
                    "selector": [
                        ".k-form-lg"
                    ]
                }
            ]
        },
        {
            "name": "orientation",
            "values": [
                {
                    "name": "vertical",
                    "selector": [
                        ".k-form-vertical"
                    ]
                },
                {
                    "name": "horizontal",
                    "selector": [
                        ".k-form-horizontal"
                    ]
                }
            ]
        }
    ],
    "children": [
        {
            "name": "form-fieldset",
            "selector": [
                ".k-form-fieldset"
            ],
            "children": [
                {
                    "name": "form-legend",
                    "selector": [
                        ".k-form-legend"
                    ]
                }
            ]
        },
        {
            "name": "form-field",
            "selector": [
                ".k-form-field"
            ],
            "states": [
                {
                    "name": "error",
                    "selector": [
                        ".k-form-field-error"
                    ]
                }
            ],
            "children": [
                {
                    "name": "form-label",
                    "selector": [
                        ".k-form-label"
                    ],
                    "children": [
                        {
                            "name": "label-optional",
                            "selector": [
                                ".k-label-optional"
                            ]
                        }
                    ]
                },
                {
                    "name": "form-field-wrap",
                    "selector": [
                        ".k-form-field-wrap"
                    ]
                },
                {
                    "name": "form-hint",
                    "selector": [
                        ".k-form-hint"
                    ]
                },
                {
                    "name": "form-error",
                    "selector": [
                        ".k-form-error"
                    ]
                }
            ]
        },
        {
            "name": "form-buttons",
            "selector": [
                ".k-form-buttons"
            ]
        },
        {
            "name": "form-autocomplete",
            "$ref": "autocomplete",
            "selector": [
                ".k-form-autocomplete"
            ]
        },
        {
            "name": "form-combobox",
            "$ref": "combobox",
            "selector": [
                ".k-form-combobox"
            ]
        },
        {
            "name": "form-dateinput",
            "$ref": "dateinput",
            "selector": [
                ".k-form-dateinput"
            ]
        },
        {
            "name": "form-datepicker",
            "$ref": "datepicker",
            "selector": [
                ".k-form-datepicker"
            ]
        },
        {
            "name": "form-datetimepicker",
            "$ref": "datetimepicker",
            "selector": [
                ".k-form-datetimepicker"
            ]
        },
        {
            "name": "form-dropdown",
            "$ref": "dropdown",
            "selector": [
                ".k-form-dropdown"
            ]
        },
        {
            "name": "form-maskedtextbox",
            "$ref": "maskedtextbox",
            "selector": [
                ".k-form-maskedtextbox"
            ]
        },
        {
            "name": "form-multiselect",
            "$ref": "multiselect",
            "selector": [
                ".k-form-multiselect"
            ]
        },
        {
            "name": "form-numerictextbox",
            "$ref": "numerictextbox",
            "selector": [
                ".k-form-numerictextbox"
            ]
        },
        {
            "name": "form-searchbox",
            "$ref": "searchbox",
            "selector": [
                ".k-form-searchbox"
            ]
        },
        {
            "name": "form-textarea",
            "$ref": "textarea",
            "selector": [
                ".k-form-textarea"
            ]
        },
        {
            "name": "form-textbox",
            "$ref": "textbox",
            "selector": [
                ".k-form-textbox"
            ]
        },
        {
            "name": "form-timedurationpicker",
            "$ref": "timedurationpicker",
            "selector": [
                ".k-form-timedurationpicker"
            ]
        },
        {
            "name": "form-timepicker",
            "$ref": "timepicker",
            "selector": [
                ".k-form-timepicker"
            ]
        },
        {
            "name": "form-checkbox",
            "$ref": "checkbox",
            "selector": [
                ".k-form-checkbox"
            ]
        }
    ]
}
